name: pr_widget
description: Pr Widget is customize widget for speed up development with custom StreamBuilder and Widget Component relate with api respose.
version: 0.0.6+3
homepage: https://github.com/ReounKompheareak/pr-widget
environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Using dio for customize api exception
  dio: ^3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/
